### ISSUE TITLE
kubectl not found even already installed

### ISSUE THREAD

**Issue by Hafzan-250601** [madhuakula/kubernetes-goat#120]
![image](https://github.com/madhuakula/kubernetes-goat/assets/54774679/291547b5-fd31-448c-848e-62dff4e44d2f)

Hi as you can see I am unable to runt he script because it said that kubectl is not found. I already installed it and it running perfectly fine, please help me on this.

**Comment by madhuakula** [comment]
Hmm, interesting. If you don't mind, could you please run the commands manually from the script just to see and debug?

Thanks

**Comment by tabacmend** [comment]
Hi @Hafzan-250601 ,
I had the same problem.

Kindly note that when you run `kubectl version` the kubectl is looking for a master cluster on port 8080 - since there isn't such you can exit code 1 and the setup script fails:
`WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
The connection to the server localhost:8080 was refused - did you specify the right host or port?

echo $?
1
`

Since I'm running this as a test, I installed [minikube](https://minikube.sigs.k8s.io/docs/start/) and started it - then all is working fine.

**Comment by za** [comment]
> I installed [minikube](https://minikube.sigs.k8s.io/docs/start/) and started it - then all is working fine

Hi @Hafzan-250601 Do you still face the issue? Have you tried above suggestion?

If the above suggestion solves the issue, we can resolve/close this.

**Comment by madhuakula** [comment]
Fixed and pushed the changes. Thanks to @pichuang
